CREATE TABLE ISSUESLISTS 
(
ID SERIAL PRIMARY KEY,
NAME CHAR(100)
)

CREATE TABLE ISSUES 
(
ID SERIAL PRIMARY KEY,
ISSUESLIST_ID BIGINT UNSIGNED,
FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
SUMMARY CHAR(100),
DESCRIPTION VARCHAR(1200),
USER_ID_ASSIGNEDTO BIGINT UNSIGNED
)

INSERT INTO ISSUESLISTS (NAME)
VALUES ("To Do");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("In progress");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (1, "READ A BOOK", "READ SOME NOVEL FROM JAMES J.", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (1, "DRING COFFE", "BREW AND PREPARE COFFEE", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (1, "CLEAN THE ATTIC", "ATKE YOUR SWEEP AT ALL THOSE SHEEP", 2);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (1, "WATER THE PLANT", "NOT TOO MUCH WATER, THAT IS.", 5);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (1, "TAKE A NAP", "ONLY AFTER 5 P.M.", 4);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (2, "WASH YOUR CAR", "MANUALLY", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (2, "PLAY PS6", "HORIZON ZERO DAWN: SIBERIA", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (2, "LEARN SOME JAVA", "ARRAYLISTS", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (2, "PREPARE DINNER", "MEATBALS WITH SPAGHETTI", 4);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (2, "MEND THE CLOCK", "ITS'S RUNNING LATE", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "WASH DISHES", "AFTER DINNER", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "READ A BOOK", "READ SOME NOVEL FROM EMILY DICKINSON", 2);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "READ A BOOK", "ON JAVA", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "VISIT FRIENDS", "CALL THEM EARLY", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "UPDATE CALENDAR", "CHANGES TO 6 P.M. MEETING", 5);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO) 
VALUES (3, "RETIRE", "AFTER 70", 1);

COMMIT;