SELECT I.SUMMARY AS TASKS_LIST, L.NAME AS NAME_OF_TASKS, I.ISSUESLIST_ID, L.ID
FROM ISSUES I
JOIN ISSUESLISTS L ON I.ISSUESLIST_ID = L.ID;

SELECT I.SUMMARY AS TASKS_LIST, U.FIRSTNAME AS FIRSTNAME, U.LASTNAM AS LASTNAME
FROM ISSUES I
JOIN USERS U ON I.ISSUESLIST_ID= U.ID;

SELECT U.FIRSTNAE, U.LSATNAME, COUNT(*), I.SUMMARY
FROM USERS U
JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY USER_ID_ ASSIGNEDTO;
