SELECT *
FROM ISSUES I
JOIN ISSUESLISTS L ON I.ISSUESLIST_ID = L.ID;

SELECT I.SUMMARY AS TASKS_LIST, U.FIRSTNAME AS FIRSTNAME, U.LASTNAME AS LASTNAME
FROM ISSUES I
JOIN USERS U ON I.ISSUESLIST_ID = U.ID;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(I.USER_ID_ASSIGNEDTO) as NO_OF_TASKS_ASSIGNED_TO_USER
FROM USERS U
JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0;
